---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-log-alerter-zulip.fullname" . }}
  labels:
    {{- include "k8s-log-alerter-zulip.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "zulip": {{ .Values.zulip | toJson }}
      ,
      "rules": {{ .Values.rules | toJson }}
    }
