name: Build
on:
  push:
    paths:
      - '.github/workflows/**'
      - '**/*zizmor*'
  pull_request:
    paths:
      - '.github/workflows/**'
      - '**/*zizmor*'

permissions:
  contents: read

jobs:
  zizmorlint:
    name: Zizmor
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@v0.3.0
        with:
          advanced-security: false
